# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'book'
    volumes:
      - ./mydb:/var/lib/mysql

  adminer:
    image: adminer:4.7.8
    restart: always
    ports:
      - 8080:8080
